version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always
    networks:
      - vibepay-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vibepay-network
    restart: always

networks:
  vibepay-network:
    driver: bridge

volumes:
  mongodb_data: 